# Generated by Django 4.2.7 on 2023-12-07 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GioiThieuViecLam', '0002_company_user_id_user_avatar_user_location_user_major_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='user_id',
            new_name='user',
        ),
    ]
