# Generated by Django 4.2.7 on 2024-01-28 07:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GioiThieuViecLam', '0004_comment_active_alter_comment_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='link_cv',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='out_off_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
