# Generated by Django 4.2.7 on 2024-01-28 07:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GioiThieuViecLam', '0005_cv_link_cv_alter_company_active_alter_company_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
