# Generated by Django 4.2.7 on 2024-01-28 08:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GioiThieuViecLam', '0006_alter_cv_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='link_cv',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='linkCv'),
            preserve_default=False,
        ),
    ]
