# Generated by Django 4.2.7 on 2024-01-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GioiThieuViecLam', '0008_alter_cv_link_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='link_cv',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
