# Generated by Django 4.2.7 on 2024-02-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GioiThieuViecLam', '0009_alter_cv_link_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='urlAvatar',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
