# Generated by Django 4.2.7 on 2024-02-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GioiThieuViecLam', '0009_alter_cv_link_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='url_avatar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
