# Generated by Django 4.2.7 on 2024-02-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GioiThieuViecLam', '0010_user_role_user_urlavatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='urlAvatar',
            new_name='url_avatar',
        ),
    ]
