# Generated by Django 4.2.7 on 2024-02-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GioiThieuViecLam', '0010_remove_user_avatar_user_role_user_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='url_avatar',
            new_name='avatar',
        ),
    ]
