# Generated by Django 4.2.7 on 2024-02-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GioiThieuViecLam', '0011_rename_urlavatar_user_url_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cv',
            name='link_cv',
            field=models.CharField(default=0.0010891089108910892, max_length=255),
            preserve_default=False,
        ),
    ]
